title:            "seamusdarcy.com"
url:              http://www.seamusdarcy.com
permalink:        pretty
google_analytics: UA-102964801-1
timezone:         Europe/Dublin
sass:
  sass_dir: assets
  style: :compressed
gems:
  - jemoji

